# Generated by Django 4.1.3 on 2022-11-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('type', models.CharField(max_length=50)),
                ('overviwe', models.TextField()),
                ('create_year', models.DateField()),
                ('number_all_students', models.IntegerField()),
                ('number_international_students', models.IntegerField()),
                ('url', models.URLField()),
                ('rate', models.IntegerField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.country'),
        ),
    ]
